### ISSUE TITLE
BABY CPU Scheduler

### ISSUE THREAD

**Issue by archdevlab** [hamadmarri/linux-baby#2]
Hi, thanks for your hard work. Can you create a repo for BABY Scheduler? Like you did for ECHO Scheduler?

Thanks!

**Comment by hamadmarri** [comment]
> Hi, thanks for your hard work. Can you create a repo for BABY Scheduler? Like you did for ECHO Scheduler?
> 
> Thanks!

Hi @archdevlab 
There is already one but it is not updated 
https://github.com/hamadmarri/Baby-CPU-Scheduler
