### ISSUE TITLE
Build error in function migrate_degrades_locality

### ISSUE THREAD

**Issue by archdevlab** [hamadmarri/linux-baby#3]
Hi I get this build error

> 
> In file included from kernel/sched/bs.c:773:
> kernel/sched/balancer.h: In function ‘migrate_degrades_locality’:
> kernel/sched/balancer.h:349:13: error: implicit declaration of function ‘sched_idle_cpu’ [-Werror=implicit-function-declaration]
>   349 |         if (sched_idle_cpu(cpu_of(dst_rq)))
>       |             ^~~~~~~~~~~~~~

linux kernel 6.7.10

tree used to path the kernel linux-6.7.y-baby

Here is the config file from Archlinux  https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/blob/0bd29eb1601f9b1d256cf8b402ba7d5e2a04b441/config

The workarroung was to disable numa

Same issue in the linux-6.7.y-echo tree

**Comment by hamadmarri** [comment]
> Hi I get this build error
> 
> > In file included from kernel/sched/bs.c:773:
> > kernel/sched/balancer.h: In function ‘migrate_degrades_locality’:
> > kernel/sched/balancer.h:349:13: error: implicit declaration of function ‘sched_idle_cpu’ [-Werror=implicit-function-declaration]
> > 349 |         if (sched_idle_cpu(cpu_of(dst_rq)))
> > |             ^~~~~~~~~~~~~~
> 
> linux kernel 6.7.10
> 
> tree used to path the kernel linux-6.7.y-baby
> 
> Here is the config file from Archlinux https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/blob/0bd29eb1601f9b1d256cf8b402ba7d5e2a04b441/config
> 
> The workarroung was to disable numa
> 
> Same issue in the linux-6.7.y-echo tree

Thank you @archdevlab 

it is fixed with this commit https://github.com/hamadmarri/linux-baby/commit/d6cc0c3fa5e790118f510fafa18642b3fd080da3
